### ISSUE TITLE
TODO + optional todo

### ISSUE THREAD

**Issue by adameus03** [adameus03/dsp_tool#1]
- [ ] (optional) Add presentation mode (checkbox in gui)
- [ ] (optional) Add default paramer values for presentation mode
- [ ] Fix histogram for heaviside and avoid trimmed histogram bars
- [x] Human-readable file output
- [ ] (optional) Human-readable file input
- [ ] (optional) User-adjustable point size for gnuplot
- [ ] (optional) User-adjustable y limits for gnuplot
- [ ] (optional) Automatically set sampling frequency ???
