### ISSUE TITLE
Task 04 - checklist

### ISSUE THREAD

**Issue by adameus03** [adameus03/dsp_tool#4]
### Implementation
- [x] Implement DFT "from definition"
- [x] Implement DIT FFT
- [x] Implement Walsh-Hadamard
- [x] Implement Fast Walsh-Hadamard
- [x] Enable complex signal plotting (how much?) - differentiate between Re/Im & arg/mag plotting
- [x] Measure execution time of transforms
- [x] Extend GUI for selecting which transform and which WH to evaluate 
- [ ] Enable saving and loading complex signals (fie IO)

### Other
- [ ] Do experiments for 3 functions (specified in the task requirements)
- [ ] Prepare report
